#ifndef PCIEMU_HW_H
#define PCIEMU_HW_H

#define AURORA_HW

#ifdef AURORA_HW
#include "pciemu/aurora_backend/aurora_hw.h"

#define PCIEMU_HW_VENDOR_ID AURORA_HW_VENDOR_ID
#define PCIEMU_HW_DEVICE_ID AURORA_HW_DEVICE_ID
#define PCIEMU_HW_REVISION AURORA_HW_REVISION

/* BAR */
#define PCIEMU_HW_BAR0 AURORA_HW_BAR0
#define PCIEMU_HW_SIZE_BAR0 AURORA_HW_SIZE_BAR0
#define PCIEMU_HW_BAR1 AURORA_HW_BAR1
#define PCIEMU_HW_SIZE_BAR1 AURORA_HW_SIZE_BAR1
#define PCIEMU_HW_BAR_CNT AURORA_HW_BAR_CNT


/* BAR0 - HARDWARE REGISTERS */
#define PCIEMU_HW_BAR0_REG_CNT AURORA_HW_BAR0_REG_CNT
#define PCIEMU_HW_BAR0_REG_0 AURORA_HW_BAR0_REG_0
#define PCIEMU_HW_BAR0_REG_1 AURORA_HW_BAR0_REG_1
#define PCIEMU_HW_BAR0_REG_2 AURORA_HW_BAR0_REG_2
#define PCIEMU_HW_BAR0_REG_3 AURORA_HW_BAR0_REG_3

/* BAR0 - IRQ */
#define PCIEMU_HW_BAR0_IRQ_0_RAISE AURORA_HW_BAR0_IRQ_0_RAISE
#define PCIEMU_HW_BAR0_IRQ_0_LOWER AURORA_HW_BAR0_IRQ_0_LOWER

/* BAR0 - DMA configuration */
#define PCIEMU_HW_BAR0_DMA_CFG_TXDESC_SRC AURORA_HW_BAR0_DMA_CFG_TXDESC_SRC
#define PCIEMU_HW_BAR0_DMA_CFG_TXDESC_DST AURORA_HW_BAR0_DMA_CFG_TXDESC_DST
#define PCIEMU_HW_BAR0_DMA_CFG_TXDESC_LEN AURORA_HW_BAR0_DMA_CFG_TXDESC_LEN
#define PCIEMU_HW_BAR0_DMA_CFG_CMD AURORA_HW_BAR0_DMA_CFG_CMD
#define PCIEMU_HW_BAR0_DMA_DOORBELL_RING AURORA_HW_BAR0_DMA_DOORBELL_RING

/* BAR0 - MSIX range */
#define PCIEMU_HW_BAR0_MSIX_TABLE AURORA_HW_BAR0_MSIX_TABLE
#define PCIEMU_HW_BAR0_MSIX_PBA AURORA_HW_BAR0_MSIX_PBA

/* BAR0 Boundaries */
#define PCIEMU_HW_BAR0_START AURORA_HW_BAR0_START
#define PCIEMU_HW_BAR0_END AURORA_HW_BAR0_END

/* DMA */
#define PCIEMU_HW_DMA_ADDR_CAPABILITY AURORA_HW_DMA_ADDR_CAPABILITY
#define PCIEMU_HW_DMA_AREA_START AURORA_HW_DMA_AREA_START
#define PCIEMU_HW_DMA_AREA_SIZE AURORA_HW_DMA_AREA_SIZE

/* DMA Commands expliciting direction of transfer */
#define PCIEMU_HW_DMA_DIRECTION_TO_DEVICE AURORA_HW_DMA_DIRECTION_TO_DEVICE
#define PCIEMU_HW_DMA_DIRECTION_FROM_DEVICE AURORA_HW_DMA_DIRECTION_FROM_DEVICE

/* MSI IRQs */
#define PCIEMU_HW_IRQ_CNT AURORA_HW_IRQ_CNT
#define PCIEMU_HW_IRQ_VECTOR_START AURORA_HW_IRQ_VECTOR_START
#define PCIEMU_HW_IRQ_VECTOR_END AURORA_HW_IRQ_VECTOR_END
#define PCIEMU_HW_IRQ_INTX AURORA_HW_IRQ_INTX /* INTA */

/* MSI-X IRQs */
#define PCIEMU_HW_IRQ_MSIX_CNT AURORA_HW_IRQ_MSIX_CNT
#define PCIEMU_HW_IRQ_MSIX_VECTOR_START AURORA_HW_IRQ_MSIX_VECTOR_START
#define PCIEMU_HW_IRQ_MSIX_VECTOR_END AURORA_HW_IRQ_MSIX_VECTOR_END


/* IRQs for DMA */
#define PCIEMU_HW_IRQ_DMA_ENDED_VECTOR AURORA_HW_IRQ_DMA_ENDED_VECTOR
#define PCIEMU_HW_IRQ_DMA_ENDED_ADDR AURORA_HW_IRQ_DMA_ENDED_ADDR
#define PCIEMU_HW_IRQ_DMA_ACK_ADDR AURORA_HW_IRQ_DMA_ACK_ADDR

#elif

#endif

#endif /* PCIEMU_HW_H */
