#ifndef _PCIEMU_IOCTL_H_
#define _PCIEMU_IOCTL_H_

#define PCIEMU_IOCTL_MAGIC 0xE1

#define PCIEMU_IOCTL_DMA_TO_DEVICE _IOW(PCIEMU_IOCTL_MAGIC, 1, void *)
#define PCIEMU_IOCTL_DMA_FROM_DEVICE _IOR(PCIEMU_IOCTL_MAGIC, 2, void *)

#endif /* _PCIEMU_IOCTL_H_ */
