#ifndef AURORA_HW_H
#define AURORA_HW_H

#define AURORA_HW_VENDOR_ID 0x1b36
#define AURORA_HW_DEVICE_ID 0x1100
#define AURORA_HW_REVISION 0x01

/* BAR */
#define AURORA_HW_BAR0 0
#define AURORA_HW_SIZE_BAR0 0x00004000
#define AURORA_HW_BAR1 1
#define AURORA_HW_SIZE_BAR1 0x40000000
#define AURORA_HW_BAR_CNT 2


/* BAR0 - HARDWARE REGISTERS */
#define AURORA_HW_BAR0_REG_CNT 4
#define AURORA_HW_BAR0_REG_0 0x00
#define AURORA_HW_BAR0_REG_1 0x08
#define AURORA_HW_BAR0_REG_2 0x10
#define AURORA_HW_BAR0_REG_3 0x18

/* BAR0 - IRQ */
#define AURORA_HW_BAR0_IRQ_0_RAISE 0x20
#define AURORA_HW_BAR0_IRQ_0_LOWER 0x28

/* BAR0 - DMA configuration */
#define AURORA_HW_BAR0_DMA_CFG_TXDESC_SRC 0x30
#define AURORA_HW_BAR0_DMA_CFG_TXDESC_DST 0x38
#define AURORA_HW_BAR0_DMA_CFG_TXDESC_LEN 0x40
#define AURORA_HW_BAR0_DMA_CFG_CMD 0x48
#define AURORA_HW_BAR0_DMA_DOORBELL_RING 0x50

/* BAR0 - MSIX range */
#define AURORA_HW_BAR0_MSIX_TABLE 0x1000
#define AURORA_HW_BAR0_MSIX_PBA 0x3000

/* BAR0 Boundaries */
#define AURORA_HW_BAR0_START AURORA_HW_BAR0_REG_0
#define AURORA_HW_BAR0_END AURORA_HW_SIZE_BAR0

/* DMA */
#define AURORA_HW_DMA_ADDR_CAPABILITY 32
#define AURORA_HW_DMA_AREA_START 0x10000
#define AURORA_HW_DMA_AREA_SIZE 0x1000

/* DMA Commands expliciting direction of transfer */
#define AURORA_HW_DMA_DIRECTION_TO_DEVICE 0x1
#define AURORA_HW_DMA_DIRECTION_FROM_DEVICE 0x2

/* MSI IRQs */
#define AURORA_HW_IRQ_CNT 1
#define AURORA_HW_IRQ_VECTOR_START 0
#define AURORA_HW_IRQ_VECTOR_END 0
#define AURORA_HW_IRQ_INTX 0 /* INTA */

/* MSI-X IRQs */
#define AURORA_HW_IRQ_MSIX_CNT 128
#define AURORA_HW_IRQ_MSIX_VECTOR_START 0
#define AURORA_HW_IRQ_MSIX_VECTOR_END 127


/* IRQs for DMA */
#define AURORA_HW_IRQ_DMA_ENDED_VECTOR 0
#define AURORA_HW_IRQ_DMA_ENDED_ADDR AURORA_HW_BAR0_IRQ_0_RAISE
#define AURORA_HW_IRQ_DMA_ACK_ADDR AURORA_HW_BAR0_IRQ_0_LOWER

#endif /* AURORA_HW_H */
