#ifndef AURORA_HW_H
#define AURORA_HW_H

#define AURORA_HW_VENDOR_ID 0x1b36
#define AURORA_HW_DEVICE_ID 0x1100
#define AURORA_HW_REVISION 0x01

/* BAR */
#define AURORA_HW_MEM_BAR 0
#define AURORA_HW_MEM_BAR_SIZE 0x800000000
#define AURORA_HW_MEM_BAR_PREFETCHABLE 0x1
#define AURORA_HW_MEM_BAR_WIDE 64

#define AURORA_HW_INT_BAR 2
#define AURORA_HW_INT_BAR_SIZE 0x200000
#define AURORA_HW_INT_BAR_PREFETCHABLE 0x0
#define AURORA_HW_INT_BAR_WIDE 32

#define AURORA_HW_REG_BAR 3
#define AURORA_HW_REG_BAR_SIZE 0x8000000
#define AURORA_HW_REG_BAR_PREFETCHABLE 0x0
#define AURORA_HW_REG_BAR_WIDE 32

#define AURORA_HW_BAR_CNT 3


/* BAR0 - HARDWARE REGISTERS */
#define AURORA_HW_REGBAR_REG_CNT 4
#define AURORA_HW_REG_0 0x00
#define AURORA_HW_REG_1 0x08
#define AURORA_HW_REG_2 0x10
#define AURORA_HW_REG_3 0x18

/* BAR0 - IRQ */
#define AURORA_HW_REG_IRQ_0_RAISE 0x20
#define AURORA_HW_REG_IRQ_0_LOWER 0x28

/* BAR0 - DMA configuration */
#define AURORA_HW_REG_DMA_CFG_TXDESC_SRC 0x30
#define AURORA_HW_REG_DMA_CFG_TXDESC_DST 0x38
#define AURORA_HW_REG_DMA_CFG_TXDESC_LEN 0x40
#define AURORA_HW_REG_DMA_CFG_CMD 0x48
#define AURORA_HW_REG_DMA_DOORBELL_RING 0x50

/* BAR0 - MSIX range */
#define AURORA_HW_MSIX_TABLE_OFFSET 0x1000
#define AURORA_HW_MSIX_PBA_OFFSET 0x3000

/* BAR0 Boundaries */
#define AURORA_HW_REGBAR_START AURORA_HW_REG_0
#define AURORA_HW_REGBAR_END AURORA_HW_REG_BAR_SIZE

/* DMA */
#define AURORA_HW_DMA_ADDR_CAPABILITY 32
#define AURORA_HW_DMA_AREA_START 0x10000
#define AURORA_HW_DMA_AREA_SIZE 0x1000

/* DMA Commands expliciting direction of transfer */
#define AURORA_HW_DMA_DIRECTION_TO_DEVICE 0x1
#define AURORA_HW_DMA_DIRECTION_FROM_DEVICE 0x2

/* MSI IRQs */
#define AURORA_HW_IRQ_CNT 1
#define AURORA_HW_IRQ_VECTOR_START 0
#define AURORA_HW_IRQ_VECTOR_END 0
#define AURORA_HW_IRQ_INTX 0 /* INTA */

/* MSI-X IRQs */
#define AURORA_HW_IRQ_MSIX_CNT 128
#define AURORA_HW_IRQ_MSIX_VECTOR_START 0
#define AURORA_HW_IRQ_MSIX_VECTOR_END 127


/* IRQs for DMA */
#define AURORA_HW_IRQ_DMA_ENDED_VECTOR 0
#define AURORA_HW_IRQ_DMA_ENDED_ADDR AURORA_HW_REG_IRQ_0_RAISE
#define AURORA_HW_IRQ_DMA_ACK_ADDR AURORA_HW_REG_IRQ_0_LOWER

#endif /* AURORA_HW_H */
